services:
  bamboo-server:
    image: eduard256/bamboo-server:latest
    container_name: bamboo-server
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./web:/app/web:ro
    sysctls:
      - net.ipv4.ip_forward=1
